FROM ubuntu:latest
RUN apt-get update && apt-get install -y python3 python3-pip
COPY requirements.txt .
RUN pip3 install -r requirements.txt
COPY my_app.py /app/
WORKDIR /app
CMD ["python3", "my_app.py"]